name: hwaet

on:
  workflow_dispatch:
  schedule:
    # test the cron ("Min Hour Day Month DayofWeek" in UTC) at scheduled time 
    - cron: "03 13 * * *" # this is 9:03 AM Eastern Standard Time

permissions:
  contents: write

jobs:
  run-hwaet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout logicalgraphs.github.io
        uses: actions/checkout@v4

      - name: Checkout protocol
        uses: actions/checkout@v4
        with: 
          repository: pivoteur/protocol
          path: protocol

      - name: Checkout crypto-n-rust
        uses: actions/checkout@v4
        with:
          repository: logicalgraphs/crypto-n-rust
          path: crypto-n-rust

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with: 
          workspaces: protocol/dapps/hwaet

      - name: Base variables
        run: |
          echo "DAPP=hwaet" >> $GITHUB_ENV
          echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "LGI=logicalgraphs.github.io" >> $GITHUB_ENV
          echo "DAPPS_DIR=protocol/dapps" >> $GITHUB_ENV
          echo "TARGET_DIR=target/release" >> $GITHUB_ENV
          echo "GIT_RAW_URL=https://raw.githubusercontent.com" >> $GITHUB_ENV

      - name: Establish pathing to dapps
        run: |
          echo "DPATH=$DAPPS_DIR/$DAPP" >> $GITHUB_ENV
          echo "PROTOCOL=logicalgraphs/$LGI" >> $GITHUB_ENV

      - name: protocol URL and paths to dapps
        run: |
          echo "LG_URL=$GIT_RAW_URL/$PROTOCOL" >> $GITHUB_ENV
          echo "GIT_DAPPS_DIR=$GITHUB_WORKSPACE/$DPATH" >> $GITHUB_ENV

      - name: PATH
        run: |
          echo "$GIT_DAPPS_DIR/$TARGET_DIR" >> $GITHUB_PATH

      - name: Build hwaet
        run: |
          cargo build --manifest-path $DPATH/Cargo.toml --bin $DAPP --release

      - name: Run hwaet
        run: hwaet lg $LE_DATE > libs/pool-health.js

      - name: Commit and push results
        env: 
          USER0_NAME: ${{ vars.USER0_NAME }}
          USER0_EMAIL: ${{ secrets.USER0_EMAIL }}
        run: |
          git config --local user.name "$USER0_NAME"
          git config --local user.email "$USER0_EMAIL"
          git add libs/pool-health.js

          if git diff --staged --quiet; then
            echo "Nothing to commit, skipping push"
            exit 0
          fi

          git commit -m "hwaet $LE_DATE"
          git push

